### UPLOAD
POST http://localhost:8080/api/v1/attach/upload/private
Authorization: Basic user:
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="wallpaperflare.com_wallpaper.jpg"

< C:\wallpaperflare.com_wallpaper.jpg

### OPEN GENERAL
GET http://localhost:8080/api/v1/attach/open_general/dd7d0bd2-fd06-4faf-878d-999e4d7e9191

### DOWNLOAD
GET http://localhost:8080/api/v1/attach/download/wallpaperflare.com_wallpaper.jpg

### DELETE
DELETE http://localhost:8080/api/v1/attach/deleteById/b67fcd30-d05a-473a-b748-cbb826ac6154


