### Login
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "kholmuminovruzibek@gmail.com",
  "password": "2211"
}
### Login 2
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "hcgvjbkn@mail.ru",
  "password": "09876"
}

### Registration
POST http://localhost:8080/api/v1/auth/registration
Content-Type: application/json

{
  "name": "Toshmat",
  "surname": "Toshmatov",
  "email": "kholmuminovruzibek@gmail.com",
  "phone": "991234567",
  "password": "2211"
}