### UPLOAD
POST http://localhost:8080/api/v1/attach/private/upload
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQ0MTE5MTIsImVtYWlsIjoia2hvbG11bWlub3ZydXppYmVrQGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNjg0NDk4MzEyLCJpc3MiOiJLdW51eiB0ZXN0IHBvcnRhbGkifQ.Y0SjPIbR8IDQLXI3fT20I2wwq7khxTWMeJYDGW2gLl0nZiXlF8V6Pz57Nk47-vsgzmNwrmB1JDI1PmDqixZu-g
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="wallpaperflare.com_wallpaper.jpg"

< C:\wallpaperflare.com_wallpaper.jpg

### OPEN GENERAL
GET http://localhost:8080/api/v1/attach/public/open_general/b3b94977-2001-4c26-9cb8-6dfac5a3dc22


### DOWNLOAD
GET http://localhost:8080/api/v1/attach/public/download/b3b94977-2001-4c26-9cb8-6dfac5a3dc22


### DELETE
DELETE http://localhost:8080/api/v1/attach/private/deleteById/b67fcd30-d05a-473a-b748-cbb826ac6154


