### Create profile
POST localhost:8080/api/v1/profile/adm/create
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQ1OTQzODksImVtYWlsIjoia2hvbG11bWlub3ZydXppYmVrQGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNjg0NjgwNzg5LCJpc3MiOiJLdW51eiB0ZXN0IHBvcnRhbGkifQ.x72T_e6bplkov4WAvxA-iTht5yDPFMuyo3ury1MMRqJlQaKHIBfarCVqtBKvP0nlFW0n2MULLqO-t1OA7gYkOQ
Content-Type:  application/json

{
  "name": "sdfgfs",
  "surname": "asdfdf",
  "email": "sdddfdds@mail.ru",
  "phone": "4352",
  "password": "34525",
  "role": "ROLE_USER"
}

### Profile List with pagination
GET http://localhost:8080/api/v1/profile/list-paging

### Profile get by id
GET http://localhost:8080/api/v1/profile/4

### Profile delete by id
DELETE http://localhost:8080/api/v1/profile/5

### Profile update by Id with Admin
PUT http://localhost:8080/api/v1/profile/5
Content-Type: application/json

{
  "name": "sfvfg"
}

### Profile update by Id
PUT http://localhost:8080/api/v1/profile/5
Content-Type: application/json

{
  "name": "sfvfg"
}

###
PUT http://localhost:8080/api/v1/profile/update/5
Content-Type: application/json

{
  "name": "Toshmat",
  "surname": "Toshmatov",
  "phone": 12345,
  "password": "653"
}
